apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory-app
          image: public.ecr.aws/c4g4u0w2/inventory-manager-1:latest
          ports:
            - containerPort: 5000
